using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace ComputerysProfanityFilter {
    public static class DefaultProfanityList {
        // U+FFFF (noncharacter)
        public const char Boundary = '\uFFFF';

        public static readonly IReadOnlyDictionary<char, string> CharacterMap = new ReadOnlyDictionary<char, string>(new Dictionary<char, string> {
            // 1337
            ['4'] = "a",
            ['@'] = "a",
            ['8'] = "b",
            ['ß'] = "b",
            ['<'] = "c",
            ['¢'] = "c",
            ['3'] = "e",
            ['€'] = "e",
            ['#'] = "h",
            ['!'] = "i",
            ['1'] = "i",
            ['|'] = "i",
            ['¡'] = "i",
            ['0'] = "o",
            ['5'] = "s",
            ['$'] = "s",
            ['+'] = "t",
            ['7'] = "t",
            ['¥'] = "y",
            ['2'] = "z",

            // expansions
            ['æ'] = "ae",
            ['œ'] = "oe",

            // Cyrillic
            ['а'] = "a",
            ['с'] = "c",
            ['е'] = "e",
            ['і'] = "i",
            ['о'] = "o",
            ['р'] = "p",
            ['ѕ'] = "s",
            ['х'] = "x",
            ['у'] = "y",

            // Greek
            ['α'] = "a",
            ['β'] = "b",
            ['ε'] = "e",
            ['ι'] = "i",
            ['κ'] = "k",
            ['ο'] = "o",
            ['ρ'] = "p",
            ['τ'] = "t",
            ['υ'] = "u",
            ['ν'] = "v",
            ['χ'] = "x",
        });

        public static readonly IReadOnlyDictionary<string, string> SequenceMap = new ReadOnlyDictionary<string, string>(new Dictionary<string, string> {
            [@"/\/\"] = "m",
            [@"|\/|"] = "m",
            [@"\/\/"] = "w",
            [@"|/\|"] = "w",
            [@"|\|"] = "n",
            ["|/|"] = "n",
            [@"/\/"] = "n",
            ["|-|"] = "h",
            ["|_|"] = "u",
            [@"/\"] = "a",
            [@"\/"] = "v",
            ["|3"] = "b",
            ["|)"] = "d",
            ["|<"] = "k",
            ["|{"] = "k",
            ["><"] = "x",
            ["}{"] = "x",
        });

        public static readonly IReadOnlyCollection<char> IgnorableCharacters = new ReadOnlyCollection<char>(new char[] {
            '.', '_', '-', '*', '/', '\\', '~', '^', '=', '`', '\'', '"', ',', ';', ':', '?', '!', '#', '$',
            '%', '&', '+', '@', '|', '¿', '…', '–', '—', '•', '·', '(', ')', '[', ']', '{', '}', '<', '>',
        });

        public static readonly IReadOnlyCollection<char> AllowsDouble = new ReadOnlyCollection<char>(new char[] {
            'b', 'c', 'd', 'e', 'f', 'g', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'z',
        });

        public static readonly IReadOnlyList<string> Words = new ReadOnlyCollection<string>(new string[] {
            // swears
            "arsehole",
            "asshole", "ahole",
            "asshat",
            "asswipe",
            "bastard",
            "bitch", "biatch",
            "bullshit",
            "cock",
            "cocksucker",
            "cunt", "kunt",
            "dick",
            "dickhead",
            "dipshit",
            "douchebag",
            "dumbass",
            "dumbfuck",
            "fuck", "fcuk", "fuk", "fuq", "fux", "fux0r", "fvck", "fxck",
            "fucker",
            "fucking",
            "motherfucker",
            "piss",
            "shit",
            "shithead",
            "shitty",
            "slut",
            "twat",
            "wank",
            "wanker",
            "whore",

            // insults
            "assfuck",
            "assfucker",
            "bitchass",
            "buttfuck",
            "clusterfuck",
            "cockbite",
            "cockface",
            "cockfucker",
            "cockhead",
            "cockmunch",
            "cocknugget",
            "cumdumpster",
            "cuntface",
            "dickbag",
            "dickface",
            "dickwad",
            "dickweed",
            "dumbcunt",
            "dumbshit",
            "fatass",
            "fuckboy",
            "fuckface",
            "fuckhead",
            "fucknugget",
            "fuckstick",
            "fucktard",
            "fuckwit",
            "jackass",
            "knobhead",
            "pigfucker",
            "shitbag",
            "shitcunt",
            "shitface",
            "shithole",
            "shitstain",
            "skullfuck",
            "slutbag",
            "son of a bitch",
            "twathead",
            "whoreface",

            // hate
            "baluga",
            "beaner",
            "chink",
            "cholo",
            "coon",
            "dago",
            "darkie",
            "dyke",
            "fag",
            "faggot",
            "gas the jews",
            "gayass",
            "gaybob",
            "gaydo",
            "gayfuck",
            "gayfuckist",
            "gaylord",
            "gaytard",
            "gaywad",
            "gook",
            "gypsy",
            "hitler",
            "homo",
            "kike",
            "kill all blacks",
            "kill all jews",
            "kill the blacks",
            "kill the jews",
            "lesbo",
            "mongoloid",
            "nazi", "nazism", "neonazi",
            "negro", "neger",
            "nig nog", "nig-nog",
            "nigaboo",
            "nigger", "nigga", "niga", "nigra",
            "niggle",
            "niglet",
            "nigress",
            "paki",
            "raghead",
            "rape",
            "retard", "reetard", "ritard", "r-tard", "tard",
            "sambo",
            "shemale",
            "sieg heil", "sig heil",
            "sissy",
            "spic",
            "towelhead",
            "tranny",
            "wetback",

            // self-harm
            "kill yourself", "kill your self", "kill you're self", "kys",

            // hate symbols
            "卐", "卍",
            "࿕", "࿖", "࿗", "࿘", // Google says they're swastika's, so we need to filter them.
            "ꖦ",
            "ᛋᛋ",
            "⚡⚡"
        });
    }
}
